shared: &shared
  - ".github/**"
  - "build-scripts/**"
docker:
  - *shared
  - ".dockerignore"
  - Dockerfile
  - "integration-tests/**"
rust:
  - *shared
  - "**/*.toml"
  - ".cargo/**"
  - "crates/**"
  - Cargo.lock
