[package]
name = "autoheal-rs"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.78.0"
authors = ["Kristof Mattei"]
description = "Monitoring application for docker containers"
license-file = "LICENSE"
categories = ["command-line-utilities"]
keywords = ["docker", "health"]
repository = "https://github.com/kristof-mattei/autoheal-rs"

[lints.clippy]
# don't stop from compiling / running
all = "warn"
pedantic = "warn"
cargo = "warn"
# this one causes confusion when combining variables (`foo`) and
# dereferenced variables (`foo.bar`). The latter cannot be inlined
# so we don't inline anything
uninlined-format-args = { level = "allow", priority = 127 }

[lints.rust]
let_underscore_drop = { level = "deny", priority = 127 }
non_ascii_idents = { level = "deny", priority = 127 }

[profile.dev.package.backtrace]
opt-level = 3

[features]
coverage = []

[dependencies]
backtrace = "0.3.70"
color-eyre = "0.6.3"
hashbrown = "0.14.5"
hex = "0.4.3"
http = "1.1.0"
http-body-util = "0.1.1"
hyper = { version = "1.3.1", default-features = false }
hyper-tls = { version = "0.6.0", default-features = false, features = [
    "vendored",
] }
hyper-unix-socket = "0.0.0-development"
hyper-util = { version = "0.1.3", default-features = false, features = [
    "client-legacy",
    "http1",
    "tokio",
] }
libc = "0.2.154"
percent-encoding = "2.3.1"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "signal",
    "net",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = { version = "2.5.0", features = ["expose_internals"] }
