[package]
name = "autoheal-rs"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.74.0"
authors = ["Kristof Mattei"]
description = "Monitoring application for docker containers"
license-file = "LICENSE"
categories = ["command-line-utilities"]
keywords = ["docker", "health"]
repository = "https://github.com/kristof-mattei/autoheal-rs"

[lints.clippy]
# don't stop from compiling / running
all = "warn"
pedantic = "warn"
cargo = "warn"
# this one causes confusion when combining variables (`foo`) and
# dereferenced variables (`foo.bar`). The latter cannot be inlined
# so we don't inline anything
uninlined-format-args = { level = "allow", priority = 127 }

[lints.rust]
let_underscore_drop = { level = "deny", priority = 127 }
non_ascii_idents = { level = "deny", priority = 127 }

[profile.dev.package.backtrace]
opt-level = 3

[features]
coverage = []

[dependencies]
color-eyre = "0.6.2"
hex = "0.4.3"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "time",
    "tracing-log",
] }
http-body-util = "0.1.0"
hyper = { version = "1.0.1", default-features = false }

hyper-util = { version = "0.1.1", default-features = false, features = [
    "client-legacy",
    "http1",
    "tokio",
] }

hyper-tls = { git = "https://github.com/kristof-mattei/hyper-tls", rev = "b29b0e99511d9745ff07e5922a0a66e3cb087567", features = [
    "vendored",
] }
hyper-unix-socket = "0.0.0-development"

libc = "0.2.150"
percent-encoding = "2.3.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "signal",
    "net",
] }
http = "1.0.0"
url = { version = "2.4.1", features = ["expose_internals"] }
