[package]
name = "autoheal-rs"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.73.0"
authors = ["Kristof Mattei"]
description = "Monitoring application for docker containers"
license-file = "LICENSE"
categories = ["command-line-utilities"]
keywords = ["docker", "health"]
repository = "https://github.com/kristof-mattei/autoheal-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.backtrace]
opt-level = 3

[features]
coverage = []

[dependencies]
color-eyre = "0.6.2"
hex = "0.4.3"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = [
    "env-filter",
    "time",
    "tracing-log",
] }
http-body-util = "0.1.0-rc.3"
hyper = { version = "1.0.0-rc.4", default-features = false }

hyper-util = { git = "https://github.com/hyperium/hyper-util", default-features = false, features = [
    "client",
    "http1",
], rev = "ced9f812460420017705fa7cae4dca7be9e23f4a" }

hyper-tls = { git = "https://github.com/kristof-mattei/hyper-tls", rev = "d6026c4d23a86dc545071c64a052613d2e412b49", features = [
    "vendored",
] }
hyper-unix-socket = { git = "https://github.com/kristof-mattei/hyper-unix-socket", rev = "01572fe3103857baafb0d31161ab85592810602e" }

libc = "0.2.150"
percent-encoding = "2.3.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "signal",
    "net",
] }
http = "0.2.9"
url = { version = "2.4.1", features = ["expose_internals"] }
