services:
  watch-autoheal-rs:
    build: watch-autoheal-rs
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:?}
    volumes:
      - type: bind
        source: "${DOCKER_SOCKET:-/var/run/docker.sock}"
        target: /var/run/docker.sock
    network_mode: none
